logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8000

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://jinbro.iptime.org:3306/land_moa?serverTimezone=UTC&characterEncoding=UTF-8
    username: "app_user"
    password: "@ppuser1234"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
